---
ngfw_audit_source:
  hosts:
    ngfw-auditd:
      ansible_host: 10.77.0.20
      ansible_user: ngfw
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeyChecking=yes -o ForwardAgent=no'
